apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nirdrep-ns9648k
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            autoindex on;
            autoindex_exact_size off;
            autoindex_localtime on;
            try_files $uri $uri/ =404;
        }
    }