---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "static-files-server"
  namespace: "nirdrep-ns9648k"
  labels:
    app: "static-files-server"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "static-files-server"
  template:
    metadata:
      labels:
        app: "static-files-server"
    spec:
      containers:
        - name: "nginx"
          image: "nginx:alpine"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: static-files
              mountPath: /usr/share/nginx/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: static-files
          hostPath:
            path: /mnt/nirdrep-ns9648k/lineage-renders
            type: Directory
        - name: nginx-config
          configMap:
            name: nginx-config

---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "static-files-hpa"
  namespace: "nirdrep-ns9648k"
  labels:
    app: "static-files-server"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "static-files-server"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target: 
          type: Utilization
          averageUtilization: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nirdrep-ns9648k
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
            add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
        }
    }